<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ESVA0SVA" failures="1" tests="3" name="ErrorValidations" time="35.623" errors="0" timestamp="2025-06-16T12:00:32 IST">
  <testcase classname="Tests.SeleniumDemo.ErrorValidations" name="addProductValidation" time="5.273"/>
  <testcase classname="Tests.SeleniumDemo.ErrorValidations" name="loginFailed" time="3.434">
    <skipped/>
  </testcase> <!-- loginFailed -->
  <testcase classname="Tests.SeleniumDemo.ErrorValidations" name="loginFailed" time="2.89">
    <failure type="java.lang.AssertionError" message="expected [×
Error: Incorrect login or password provided.] but found [Login failed]">
      <![CDATA[java.lang.AssertionError: expected [×
Error: Incorrect login or password provided.] but found [Login failed]
at Tests.SeleniumDemo.ErrorValidations.loginFailed(ErrorValidations.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginFailed -->
</testsuite> <!-- ErrorValidations -->
